#!/usr/bin/env python3
"""
Dynamic Ansible inventory from Wazuh API.
Writes inventory/hosts.ini matching current registered agents.
"""
import json
import os
import subprocess
import sys

WAZUH_API = "https://localhost:50001"
WAZUH_API_USER = "wazuh-wui"
WAZUH_API_PASS = os.getenv("WAZUH_API_PASSWORD", "changeme")
INVENTORY_PATH = "/root/sentinel-ai-commander/ansible/inventory/hosts.ini"
SSH_KEY = "/ansible/keys/id_rsa"

def run(cmd):
    r = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    return r.stdout.strip()

def get_token():
    out = run(f'curl -sk -X POST {WAZUH_API}/security/user/authenticate -u "{WAZUH_API_USER}:{WAZUH_API_PASS}"')
    return json.loads(out)["data"]["token"]

def get_agents(token):
    out = run(f'curl -sk "{WAZUH_API}/agents?limit=500" -H "Authorization: Bearer {token}"')
    return json.loads(out)["data"]["affected_items"]

def main():
    token = get_token()
    agents = get_agents(token)

    lines = []
    lines.append("# AUTO-GENERATED by dynamic_inventory.py")
    lines.append("# Regenerate: python3 dynamic_inventory.py")
    lines.append("")
    lines.append("[wazuh_managers]")
    lines.append("sentinel-wazuh-manager ansible_host=sentinel-wazuh-manager ansible_connection=docker")
    lines.append("")
    lines.append("[wazuh_agents]")

    agent_names = []
    for a in agents:
        if a.get("id") == "000":
            continue
        name = a.get("name")
        ip = a.get("ip", "")
        status = a.get("status", "")
        # Skip agents with no real IP (e.g., "any" means ip-unknown, use name lookup)
        # For practical remediation we need a reachable IP — try registerIP or fall back
        real_ip = ip or a.get("registerIP")
        if real_ip in ("any", "", None):
            # Try to resolve from agent name — but for Docker NAT the registerIP is usually correct
            # For now, we'll note it but skip from remediation targets
            continue
        lines.append(f"{name} ansible_host={real_ip} ansible_user=root ansible_ssh_private_key_file={SSH_KEY}")
        agent_names.append(name)

    lines.append("")
    lines.append("[linux_victims]")
    for name in agent_names:
        lines.append(name)

    lines.append("")
    lines.append("[all:vars]")
    lines.append("ansible_python_interpreter=auto_silent")
    lines.append("ansible_ssh_common_args=-o StrictHostKeyChecking=no")
    lines.append(f"wazuh_manager_ip={os.getenv('WAZUH_MANAGER_EXTERNAL_IP', '172.31.70.13')}")
    lines.append("wazuh_manager_port=50041")

    with open(INVENTORY_PATH, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Wrote {INVENTORY_PATH}")
    print(f"Agents included: {len(agent_names)}")
    for n in agent_names:
        print(f"  - {n}")

if __name__ == "__main__":
    main()
