"""
SENTINEL-AI Commander — Orchestrator (Phase 3)
===============================================
Two-path alert processor:

  FAST PATH  : rule in STATIC_RULE_MAP → immediate Ansible dispatch (Phase 2)
  PHASE 3    : unknown rule above threshold → multi-host LLM triage

Phase 3 flow:
  1. Gather deduplicated context from multiple hosts:
       - Primary   : triggering agent
       - Relay     : if src_ip resolves to an internal DMZ agent
       - Gateway   : always — Suricata network-level view
  2. Build a single LLM prompt with all three contexts + correlation instructions
  3. LLM (Cerebras → Groq → Gemini cascade) returns JSON decision
  4. Safety guards validate decision
  5. Execute via Ansible runner

No MCP server required. No Anthropic dependency.
"""

import json
import logging
import os
import re
import uuid
from typing import Any, Dict, Optional

import requests
import structlog

from ai_agents.agents.ansible_dispatch.ansible_dispatch_agent import (
    STATIC_RULE_MAP,
    AnsibleDispatchAgent,
    extract_vars_from_alert,
)
from ai_agents.agents.log_analyzer.log_analyzer import LogAnalyzerAgent
from ai_agents.config_topology import get_topology
from ai_agents.database.db_manager import get_db
from ai_agents.database.models import Incident, IncidentStatus, SeverityLevel
from ai_agents.integrations.redis_manager import get_redis
from ai_agents.tools.ansible_trigger import AnsibleTrigger

logger = structlog.get_logger()

# ── Phase 3 config ─────────────────────────────────────────────────────────────
PHASE3_ENABLED     = os.getenv("PHASE3_ENABLED",   "true").lower() == "true"
PHASE3_MIN_LEVEL   = int(os.getenv("PHASE3_MIN_LEVEL",  "7"))
PHASE3_DRY_RUN     = os.getenv("PHASE3_DRY_RUN",   "false").lower() == "true"
PHASE3_CONFIDENCE  = float(os.getenv("PHASE3_CONFIDENCE_THRESHOLD", "0.6"))
PHASE3_CONTEXT_WIN = os.getenv("PHASE3_CONTEXT_WINDOW", "30m")

# Playbooks the LLM may select
_PHASE3_ALLOWED_PLAYBOOKS = {
    "block_ip", "incident_response", "win_incident_response",
    "fim_restore_response", "win_fim_restore_response",
    "harden_nginx_tls", "mysql_credential_response",
    "block_adcs_abuse", "block_dns_exfil",
    "brute_force_response", "win_brute_force_response",
    "lateral_movement_response", "win_lateral_movement_response",
    "malware_containment", "win_malware_containment",
}

# FIM paths generated by our own Ansible runs — filter from context
_ANSIBLE_NOISE_PREFIXES = ("/tmp/ansible_", "/root/.ansible/", "/var/cache/apt/",
                            "/var/lib/apt/", "/var/log/wtmp", "/var/log/btmp",
                            "/var/log/lastlog", "/etc/cups/subscriptions")

SEVERITY_MAP = {
    "low": SeverityLevel.LOW, "medium": SeverityLevel.MEDIUM,
    "high": SeverityLevel.HIGH, "critical": SeverityLevel.CRITICAL,
}


# ─────────────────────────────────────────────────────────────────────────────
# Orchestrator
# ─────────────────────────────────────────────────────────────────────────────

class OrchestratorAgent:

    def __init__(self):
        self.log_analyzer     = LogAnalyzerAgent()
        self.ansible_dispatch = AnsibleDispatchAgent()
        self._trigger         = AnsibleTrigger()

    # ── Main entry point ──────────────────────────────────────────────────────

    async def process_alert(self, alert: dict) -> dict:
        incident_id = str(uuid.uuid4())
        rule_id_str = str(alert.get("rule", {}).get("id", ""))
        rule_level  = alert.get("rule", {}).get("level", 0)
        agent_name  = (alert.get("agent") or {}).get("name", "")

        logger.info("orchestrator.processing",
                    incident_id=incident_id,
                    rule_id=rule_id_str,
                    agent=agent_name)

        # ── FAST PATH: known rule ─────────────────────────────────────────────
        if rule_id_str in STATIC_RULE_MAP:
            dispatch_result = await self.ansible_dispatch.execute({
                "alert":      alert,
                "analysis":   "static_map_fast_path",
                "alert_type": "known_threat",
                "severity":   STATIC_RULE_MAP[rule_id_str].get("severity", "high"),
                "confidence": 0.95,
                "source_ip":  _extract_src_ip(alert),
                "incident_id": incident_id,
            })
            return {
                "incident_id": incident_id,
                "dispatch":    dispatch_result,
                "fast_path":   True,
                "phase":       "phase2_static",
            }

        # ── PHASE 3: unknown rule ─────────────────────────────────────────────
        if PHASE3_ENABLED and rule_level >= PHASE3_MIN_LEVEL:
            return await self._phase3_dispatch(
                alert, rule_id_str, agent_name, incident_id
            )

        # ── SKIP ──────────────────────────────────────────────────────────────
        logger.debug("orchestrator.skip",
                     rule_id=rule_id_str, level=rule_level,
                     reason="no_static_rule_phase3_disabled_or_below_threshold")
        return {
            "incident_id": incident_id,
            "dispatch":    {"executed": False, "reason": "no_static_rule_match"},
            "fast_path":   False,
            "phase":       "skipped",
        }

    # ── Phase 3: multi-host LLM triage ───────────────────────────────────────

    async def _phase3_dispatch(
        self,
        alert: dict,
        rule_id: str,
        agent_name: str,
        incident_id: str,
    ) -> dict:
        logger.info("orchestrator.phase3.start",
                    incident_id=incident_id,
                    rule_id=rule_id,
                    agent=agent_name)

        src_ip = _extract_src_ip(alert)

        # ── Step 1: Multi-host context gathering ─────────────────────────────
        contexts = await self._gather_multi_host_context(
            alert, rule_id, agent_name, src_ip
        )

        # ── Step 2: Enrich source IP with external threat intel ──────────────
        # Only fires for public IPs — private IPs return immediately with no API call
        threat_intel_str = await _enrich_src_ip(src_ip) if src_ip else ""

        # ── Step 3: Build prompt ──────────────────────────────────────────────
        prompt = self._build_phase3_prompt(
            alert, rule_id, agent_name, src_ip, contexts, threat_intel_str
        )

        # ── Step 4: LLM call ─────────────────────────────────────────────────
        decision = await _llm_decide(prompt)
        if decision is None:
            logger.warning("orchestrator.phase3.llm_failed",
                           incident_id=incident_id, rule_id=rule_id)
            return {
                "incident_id": incident_id,
                "phase":       "phase3_llm_failed",
                "dispatch":    {"executed": False, "reason": "llm_unavailable"},
            }

        logger.info("orchestrator.phase3.decision",
                    incident_id=incident_id,
                    rule_id=rule_id,
                    action=decision.get("action"),
                    confidence=decision.get("confidence"),
                    attributed_ip=decision.get("attributed_src_ip", ""),
                    reasoning=decision.get("reasoning", "")[:120])

        # ── Step 5: Validate ─────────────────────────────────────────────────
        action     = decision.get("action", "no_action")
        confidence = float(decision.get("confidence", 0.0))
        target     = decision.get("target_host", agent_name) or agent_name
        # Use LLM's attributed IP (may differ from alert src_ip for relay cases)
        src        = decision.get("attributed_src_ip") or decision.get("source_ip") or src_ip

        topo = get_topology()

        if action == "no_action" or action not in _PHASE3_ALLOWED_PLAYBOOKS:
            return {
                "incident_id": incident_id,
                "phase":       "phase3_llm",
                "decision":    decision,
                "dispatch":    {"executed": False,
                                "reason": f"no_action_or_invalid_playbook: {action}"},
            }

        if not topo.is_safe_to_block(src) and action in {
            "block_ip", "brute_force_response", "win_brute_force_response",
            "lateral_movement_response", "win_lateral_movement_response",
        }:
            return {
                "incident_id": incident_id,
                "phase":       "phase3_llm",
                "decision":    decision,
                "dispatch":    {"executed": False,
                                "reason": f"safety_guard: unsafe_ip_to_block: {src}"},
            }

        if confidence < PHASE3_CONFIDENCE:
            return {
                "incident_id": incident_id,
                "phase":       "phase3_llm",
                "decision":    decision,
                "dispatch":    {"executed": False,
                                "reason": f"low_confidence: {confidence}"},
            }

        if PHASE3_DRY_RUN:
            logger.info("orchestrator.phase3.dry_run",
                        playbook=action, target=target, src=src)
            return {
                "incident_id": incident_id,
                "phase":       "phase3_llm_dry_run",
                "decision":    decision,
                "dispatch":    {"executed": False, "reason": "dry_run",
                                "would_run": action, "on": target},
            }

        # ── Step 6: Execute ───────────────────────────────────────────────────
        extra_vars = extract_vars_from_alert(alert)
        extra_vars.update({
            "incident_id":  incident_id,
            "severity":     decision.get("severity", "high"),
            "source_ip":    src,
            "target_hosts": target,
            "dry_run":      False,
        })

        try:
            result = await self._trigger.run_playbook(
                playbook=action,
                extra_vars=extra_vars,
            )
            # Persist to DB
            try:
                with get_db() as db:
                    db.add(Incident(
                        id=incident_id,
                        wazuh_alert_id=str(alert.get("id", "")),
                        rule_id=int(rule_id) if rule_id.isdigit() else 0,
                        rule_description=alert.get("rule", {}).get("description"),
                        severity=SEVERITY_MAP.get(
                            decision.get("severity", "high"), SeverityLevel.HIGH
                        ),
                        status=IncidentStatus.RESPONDING,
                        source_ip=src,
                        analysis=decision.get("reasoning", ""),
                        recommended_action=action,
                        confidence_score=confidence,
                        playbook_executed=action,
                        playbook_result=result,
                        alert_data=alert,
                    ))
            except Exception as db_exc:
                logger.warning("orchestrator.phase3.db_failed", error=str(db_exc))

            return {
                "incident_id": incident_id,
                "phase":       "phase3_llm",
                "decision":    decision,
                "dispatch":    {"executed": True, "playbook": action, "result": result},
            }
        except Exception as exc:
            logger.error("orchestrator.phase3.execution_failed", error=str(exc))
            return {
                "incident_id": incident_id,
                "phase":       "phase3_llm",
                "decision":    decision,
                "dispatch":    {"executed": False, "reason": f"execution_failed: {exc}"},
            }

    # ── Multi-host context gathering ──────────────────────────────────────────

    async def _gather_multi_host_context(
        self,
        alert: dict,
        rule_id: str,
        agent_name: str,
        src_ip: str,
    ) -> dict:
        """
        Gather deduplicated context from three tiers:
          Tier 1 — Primary   : triggering agent
          Tier 2 — Relay     : if src_ip resolves to a known DMZ agent
          Tier 3 — Gateway   : network-level Suricata view (always)

        Returns {primary, relay, gateway} context dicts.
        """
        from ai_agents.rag.agent_tools import gather_alert_context
        topo = get_topology()

        def _fetch(agent: Optional[str], max_unique: int = 40) -> dict:
            try:
                ctx = gather_alert_context(
                    agent_name=agent,
                    time_window=PHASE3_CONTEXT_WIN,
                    min_level=0,
                    max_raw_alerts=500,
                    max_unique_types=max_unique,
                )
                # Filter Ansible-generated FIM noise
                ctx["unique_events"] = [
                    e for e in ctx.get("unique_events", [])
                    if not any(
                        (e.get("syscheck_path") or "").startswith(prefix)
                        for prefix in _ANSIBLE_NOISE_PREFIXES
                    )
                ]
                return ctx
            except Exception as exc:
                logger.warning("orchestrator.phase3.context_fetch_failed",
                               agent=agent, error=str(exc))
                return {"summary": {}, "mitre_summary": [], "unique_events": []}

        # Tier 1: primary (triggering agent)
        primary_ctx = _fetch(agent_name, max_unique=40)

        # Tier 2: relay detection
        relay_ctx        = None
        relay_agent_name = None
        if src_ip:
            ip_class = topo.classify_ip(src_ip)
            if ip_class == "dmz":
                relay_agent_name = topo.ip_to_agent(src_ip)
                if relay_agent_name and relay_agent_name != agent_name:
                    logger.info("orchestrator.phase3.relay_detected",
                                src_ip=src_ip, relay_agent=relay_agent_name)
                    relay_ctx = _fetch(relay_agent_name, max_unique=30)

        # Tier 3: gateway (Suricata network view)
        gateway_ctx        = None
        gateway_agent_name = topo.get_gateway_agent()
        if gateway_agent_name and gateway_agent_name != agent_name:
            gateway_ctx = _fetch(gateway_agent_name, max_unique=20)

        return {
            "primary": {
                "agent":   agent_name,
                "context": primary_ctx,
            },
            "relay": {
                "agent":   relay_agent_name,
                "context": relay_ctx,
            } if relay_ctx else None,
            "gateway": {
                "agent":   gateway_agent_name,
                "context": gateway_ctx,
            } if gateway_ctx else None,
        }

    # ── Prompt builder ────────────────────────────────────────────────────────

    def _build_phase3_prompt(
        self,
        alert: dict,
        rule_id: str,
        agent_name: str,
        src_ip: str,
        contexts: dict,
        threat_intel: str = "",
    ) -> str:
        topo        = get_topology()
        rule_desc   = alert.get("rule", {}).get("description", "")
        rule_level  = alert.get("rule", {}).get("level", 0)
        rule_groups = alert.get("rule", {}).get("groups", [])

        allowed_str   = "\n".join(f"  - {p}" for p in sorted(_PHASE3_ALLOWED_PLAYBOOKS))
        topology_str  = topo.build_prompt_topology()
        ip_rules_str  = topo.build_prompt_ip_routing()

        # Format each context tier compactly
        def _fmt(ctx: dict, label: str, note: str = "") -> str:
            if not ctx:
                return f"=== {label} ===\n  (no data)\n"
            summary = ctx.get("summary", {})
            events  = ctx.get("unique_events", [])[:25]
            mitre   = ctx.get("mitre_summary", [])
            lines   = [f"=== {label} ==="]
            if note:
                lines.append(f"  NOTE: {note}")
            lines.append(
                f"  {summary.get('unique_event_types', 0)} unique event types "
                f"from {summary.get('total_raw_alerts', 0)} raw alerts "
                f"in last {summary.get('time_window', '?')}"
            )
            if mitre:
                lines.append("  MITRE: " + ", ".join(
                    f"{m['technique_id']} {m['technique_name']} ({m['total_occurrences']}x)"
                    for m in mitre[:5]
                ))
            for e in events:
                rate  = f"@{e['rate_per_minute']}/min" if e.get("rate_per_minute") else ""
                src   = f" src={e['src_ip']}" if e.get("src_ip") else ""
                path  = f" path={e['syscheck_path']}" if e.get("syscheck_path") else ""
                lines.append(
                    f"  [{e['occurrences']:4d}x] L{e['rule_level']:02d} "
                    f"rule={e['rule_id']:8s} {e['rule_description'][:55]:55s}"
                    f"{src}{path} {rate}"
                )
            return "\n".join(lines)

        primary_str = _fmt(
            contexts["primary"]["context"],
            f"PRIMARY — triggering agent: {contexts['primary']['agent']}",
        )

        relay_str = ""
        if contexts.get("relay"):
            r = contexts["relay"]
            relay_str = "\n" + _fmt(
                r["context"],
                f"RELAY CANDIDATE — {r['agent']} (src_ip {src_ip} resolved to this agent)",
                "If this agent shows compromise from an external IP, it is a relay. "
                "The REAL attacker is that external IP, not this agent.",
            )

        gateway_str = ""
        if contexts.get("gateway"):
            g = contexts["gateway"]
            gateway_str = "\n" + _fmt(
                g["context"],
                f"NETWORK VIEW — gateway/Suricata: {g['agent']}",
                "This agent sees ALL TCP connections. "
                "Look here for the original src_ip of attacks on internal hosts.",
            )

        has_relay   = bool(contexts.get("relay"))
        has_gateway = bool(contexts.get("gateway"))

        corr_instruction = ""
        if has_relay or has_gateway:
            corr_instruction = """
CORRELATION TASK:
Cross-reference the three context blocks above.

1. If RELAY shows compromise alerts from an external IP shortly before this alert:
   - The triggering src_ip is a relay, not the real attacker
   - Set attributed_src_ip to the EXTERNAL IP you found in the relay context
   - Set target_host to the RELAY AGENT (it needs incident_response)

2. If GATEWAY shows Suricata network alerts from an external IP targeting the
   primary agent around the same time:
   - Confirms external origin
   - Use that external IP as attributed_src_ip

3. If contexts are unrelated or context is empty:
   - Use the alert src_ip directly as attributed_src_ip
   - Reduce confidence to reflect limited visibility
"""

        return f"""You are SENTINEL-AI, an automated SOC triage agent.

A Wazuh alert fired for a rule NOT in the static response map.
Analyse the alert and multi-host context, then decide on a response.

TRIGGERING ALERT:
  Rule ID      : {rule_id}
  Description  : {rule_desc}
  Level        : {rule_level} / 15
  Groups       : {rule_groups}
  Agent        : {agent_name}
  Source IP    : {src_ip or '(none — host-based detection)'}
{threat_intel}

{topology_str}

{ip_rules_str}

ALLOWED PLAYBOOKS:
{allowed_str}

RECENT ACTIVITY CONTEXT ({PHASE3_CONTEXT_WIN} window, deduplicated):
{primary_str}{relay_str}{gateway_str}
{corr_instruction}
Respond ONLY with this JSON (no other text):
{{
  "action":             "<playbook_name_or_no_action>",
  "severity":           "<low|medium|high|critical>",
  "confidence":         <0.0-1.0>,
  "attributed_src_ip":  "<true_attacker_ip_after_correlation_or_empty>",
  "source_ip":          "<alert_src_ip_or_empty>",
  "target_host":        "<agent_to_run_playbook_on>",
  "mitre_technique":    "<T1234.001_or_empty>",
  "relay_detected":     <true|false>,
  "reasoning":          "<one concise sentence explaining the decision>"
}}"""

    # ── Redis cache for fast API retrieval ────────────────────────────────────

    def _cache_incident(self, incident_id: str, result: dict, alert: dict) -> None:
        try:
            get_redis().set(f"incident:{incident_id}", {
                "incident_id": incident_id,
                "rule_id":     alert.get("rule", {}).get("id"),
                "agent":       (alert.get("agent") or {}).get("name"),
                "severity":    result.get("decision", {}).get("severity", "unknown"),
                "dispatch":    result.get("dispatch"),
                "phase":       result.get("phase"),
            })
        except Exception as exc:
            logger.warning("orchestrator.redis.failed", error=str(exc))


# ── Helpers ───────────────────────────────────────────────────────────────────

def _extract_src_ip(alert: dict) -> str:
    data = alert.get("data", {}) or {}
    win  = (data.get("win") or {}).get("eventdata") or {}
    full_log = alert.get("full_log", "") or ""
    # DoH logs carry src= in the message
    doh_match = re.search(r"src=([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)", full_log)
    if doh_match:
        return doh_match.group(1)
    return (
        data.get("srcip") or data.get("src_ip")
        or win.get("ipAddress") or win.get("ipaddress") or ""
    )


async def _enrich_src_ip(ip: str) -> str:
    """
    Enrich a source IP with external threat intelligence.
    Returns a formatted string for inclusion in the LLM prompt.
    Only queries external APIs for public IPs — private IPs return immediately.
    """
    if not ip:
        return ""
    from ai_agents.rag.agent_tools import enrich_ioc
    try:
        result = enrich_ioc(ip=ip)
        ip_intel = result.get("ip_intel", {})

        if ip_intel.get("skipped"):
            return f"THREAT INTEL: {ip} is a private/internal IP — no external data available."

        verdict = ip_intel.get("verdict", "UNKNOWN")
        abuse   = ip_intel.get("abuse_score", 0)
        sources = ip_intel.get("sources", [])

        lines = [f"THREAT INTEL for {ip} (verdict: {verdict}, abuse_score: {abuse}%)"]

        abuseipdb = ip_intel.get("abuseipdb", {})
        if abuseipdb and not abuseipdb.get("skipped") and not abuseipdb.get("error"):
            lines.append(
                f"  AbuseIPDB: {abuse}% confidence malicious | "
                f"reports={abuseipdb.get('total_reports',0)} | "
                f"country={abuseipdb.get('country','?')} | "
                f"isp={abuseipdb.get('isp','?')} | "
                f"tor={abuseipdb.get('is_tor',False)}"
            )

        gn = ip_intel.get("greynoise", {})
        if gn and not gn.get("skipped") and not gn.get("error"):
            lines.append(
                f"  GreyNoise: noise={gn.get('noise',False)} | "
                f"riot={gn.get('riot',False)} | "
                f"classification={gn.get('classification','?')} | "
                f"name={gn.get('name','?')}"
            )

        if not sources:
            lines.append("  (No API keys configured — set ABUSEIPDB_API_KEY and/or GREYNOISE_API_KEY)")

        return "\n".join(lines)
    except Exception as exc:
        logger.warning("orchestrator.enrich_failed ip=%s error=%s", ip, exc)
        return ""


async def _llm_decide(prompt: str) -> Optional[Dict[str, Any]]:
    """
    Single-shot LLM call — Cerebras → Groq → Gemini cascade.
    Returns parsed JSON dict or None if all providers fail.
    """
    providers = [
        {
            "name":  "cerebras",
            "url":   "https://api.cerebras.ai/v1/chat/completions",
            "key":   os.getenv("CEREBRAS_API_KEY", ""),
            "model": os.getenv("CEREBRAS_MODEL", "qwen-3-235b-a22b-instruct-2507"),
        },
        {
            "name":  "groq",
            "url":   "https://api.groq.com/openai/v1/chat/completions",
            "key":   os.getenv("GROQ_API_KEY", ""),
            "model": os.getenv("LLM_MODEL", "llama-3.3-70b-versatile"),
        },
        {
            "name":  "gemini",
            "url":   "https://generativelanguage.googleapis.com/v1beta/openai/chat/completions",
            "key":   os.getenv("GEMINI_API_KEY", ""),
            "model": os.getenv("GEMINI_MODEL", "gemini-2.5-flash").removeprefix("gemini/"),
        },
    ]

    for p in providers:
        if not p["key"]:
            continue
        try:
            resp = requests.post(
                p["url"],
                headers={"Authorization": f"Bearer {p['key']}",
                         "Content-Type": "application/json"},
                json={
                    "model":       p["model"],
                    "messages":    [{"role": "user", "content": prompt}],
                    "temperature": 0,
                    "max_tokens":  768,
                },
                timeout=45,
            )
            resp.raise_for_status()
            text = resp.json()["choices"][0]["message"]["content"].strip()
            # Extract JSON — handle markdown code blocks
            text = re.sub(r"```json\s*", "", text)
            text = re.sub(r"```\s*$", "", text)
            m = re.search(r"\{.*\}", text, re.DOTALL)
            if m:
                return json.loads(m.group(0))
        except Exception as exc:
            logger.warning("orchestrator.phase3.llm_provider_failed",
                           provider=p["name"], error=str(exc)[:120])
            continue

    return None
